# Generated by Django 3.0.3 on 2020-03-19 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode', models.CharField(max_length=5)),
                ('yr', models.DateTimeField(default=datetime.datetime(2020, 3, 19, 22, 11, 30, 324785))),
                ('comment', models.CharField(max_length=150)),
                ('uploader_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode', models.CharField(max_length=5)),
                ('img', models.ImageField(upload_to='pics')),
                ('yr', models.DateTimeField(default=datetime.datetime(2020, 3, 19, 22, 11, 30, 252488))),
                ('uploader_name', models.CharField(max_length=30)),
            ],
        ),
    ]
