# Generated by Django 3.0.3 on 2020-03-19 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20200319_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_solutions',
            name='ccode',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 23, 52, 33, 853092)),
        ),
        migrations.AlterField(
            model_name='materials',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 23, 52, 33, 815193)),
        ),
    ]
