# Generated by Django 3.0.3 on 2020-03-19 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20200319_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 1, 54, 45, 315060)),
        ),
        migrations.AlterField(
            model_name='materials',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 1, 54, 45, 277161)),
        ),
    ]
