# Generated by Django 3.0.3 on 2020-03-20 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_auto_20200320_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 13, 9, 30, 594367)),
        ),
        migrations.AlterField(
            model_name='materials',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='yr',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 13, 9, 30, 554473)),
        ),
    ]
